### ISSUE TITLE
Work on this more

### ISSUE THREAD

**Issue by traverseda** [cconstantine/CacheFS#1]
It's a cool project, you should work on this more :p

I wonder if one could abuse unionfs to make the whole thing a bit more transparent.

**Comment by cconstantine** [comment]
Hehe, thanks :)

Realistically I'm probably not going to have time for this, and I don't have an active use-case that could really benefit from this project.

It looks like nitmir ( https://github.com/nitmir/CacheFS ) has picked up the project recently.  Maybe they are who you should be following.

**Comment by traverseda** [comment]
Cool. I've got fiber-op internet in my region, which means 30Mb/s upload. My intent is to use this to synchronize my home folder with a master computer, including a whole bunch of large files.

Doesn't look super complicated to extend, if there's been recent activity I'll probably pitch in.
